name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: dalscooter-464600
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t gcr.io/dalscooter-464600/dalscooter-frontend:latest ./frontend

      - name: Push Docker image
        run: |
          docker push gcr.io/dalscooter-464600/dalscooter-frontend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dalscooter-frontend \
            --image gcr.io/dalscooter-464600/dalscooter-frontend:latest \
            --region northamerica-northeast1 \
            --platform managed \
            --allow-unauthenticated
