name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: dalscooter-464600

      - name: Build Docker image
        run: |
          docker build -t us-docker.pkg.dev/dalscooter-464600/gcr.io/dalscooter-frontend:latest ./frontend

      - name: Push Docker image
        run: |
          docker push us-docker.pkg.dev/dalscooter-464600/gcr.io/dalscooter-frontend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dalscooter-frontend \
            --image us-docker.pkg.dev/dalscooter-464600/gcr.io/dalscooter-frontend:latest \
            --region northamerica-northeast1 \
            --platform managed \
            --allow-unauthenticated
